<a href="https://colab.research.google.com/github/nendyannisa/Data-Mining-with-Python/blob/main/DecisionTree_Pencemaran_Udara_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn import tree

In [2]:
irisDataset = pd.read_csv('dataPencemaran.csv', delimiter=';',header=0)

In [3]:
irisDataset.head()

stasiun  co  o2 categori
0  DKI1 (Bunderan HI)  26  74     BAIK
1  DKI1 (Bunderan HI)  25  64     BAIK
2  DKI1 (Bunderan HI)  29  70     BAIK
3  DKI1 (Bunderan HI)  36  78     BAIK
4  DKI1 (Bunderan HI)  20  45     BAIK

In [4]:
irisDataset["categori"] = pd.factorize(irisDataset.categori)[0]

In [5]:
irisDataset.head()

stasiun  co  o2  categori
0  DKI1 (Bunderan HI)  26  74         0
1  DKI1 (Bunderan HI)  25  64         0
2  DKI1 (Bunderan HI)  29  70         0
3  DKI1 (Bunderan HI)  36  78         0
4  DKI1 (Bunderan HI)  20  45         0

In [6]:
print(irisDataset)

                 stasiun  co   o2  categori
0     DKI1 (Bunderan HI)  26   74         0
1     DKI1 (Bunderan HI)  25   64         0
2     DKI1 (Bunderan HI)  29   70         0
3     DKI1 (Bunderan HI)  36   78         0
4     DKI1 (Bunderan HI)  20   45         0
5     DKI1 (Bunderan HI)  37   47         0
6     DKI1 (Bunderan HI)  36   82         1
7     DKI1 (Bunderan HI)  37   98         1
8     DKI1 (Bunderan HI)  32  116         1
9     DKI1 (Bunderan HI)  48   78         0
10    DKI1 (Bunderan HI)  37   88         1
11    DKI1 (Bunderan HI)  25   73         0
12    DKI1 (Bunderan HI)  42   75         0
13    DKI1 (Bunderan HI)  37   71         0
14    DKI1 (Bunderan HI)  23   74         0
15    DKI1 (Bunderan HI)  22   41         0
16    DKI1 (Bunderan HI)  19   35         0
17    DKI1 (Bunderan HI)  22   39         0
18    DKI1 (Bunderan HI)  23   87         1
19    DKI1 (Bunderan HI)  25   82         0
20    DKI1 (Bunderan HI)  39   65         0
21    DKI1 (Bunderan HI)  34   6

In [7]:
irisDataset = irisDataset.drop(labels="stasiun", axis=1)

In [8]:
print(irisDataset)

    co   o2  categori
0   26   74         0
1   25   64         0
2   29   70         0
3   36   78         0
4   20   45         0
5   37   47         0
6   36   82         1
7   37   98         1
8   32  116         1
9   48   78         0
10  37   88         1
11  25   73         0
12  42   75         0
13  37   71         0
14  23   74         0
15  22   41         0
16  19   35         0
17  22   39         0
18  23   87         1
19  25   82         0
20  39   65         0
21  34   64         0
22  32   76         0
23  29   71         0
24  33   57         0
25  22   70         0
26  14  107         1
27  20  131         1
28  17  105         1
29  46   59         0
30  15   81         0
31  19   85         1
32  36  143         1
33  30  130         1
34  19  129         1
35  36  100         1
36  31  151         1
37  22  171         1
38  33   80         0
39  26  106         1
40  18  117         1
41  17   11         0
42  13   10         0
43  17   10         0
44  12    

In [9]:
irisDataset = irisDataset.to_numpy()

In [10]:
print(irisDataset)

[[ 26  74   0]
 [ 25  64   0]
 [ 29  70   0]
 [ 36  78   0]
 [ 20  45   0]
 [ 37  47   0]
 [ 36  82   1]
 [ 37  98   1]
 [ 32 116   1]
 [ 48  78   0]
 [ 37  88   1]
 [ 25  73   0]
 [ 42  75   0]
 [ 37  71   0]
 [ 23  74   0]
 [ 22  41   0]
 [ 19  35   0]
 [ 22  39   0]
 [ 23  87   1]
 [ 25  82   0]
 [ 39  65   0]
 [ 34  64   0]
 [ 32  76   0]
 [ 29  71   0]
 [ 33  57   0]
 [ 22  70   0]
 [ 14 107   1]
 [ 20 131   1]
 [ 17 105   1]
 [ 46  59   0]
 [ 15  81   0]
 [ 19  85   1]
 [ 36 143   1]
 [ 30 130   1]
 [ 19 129   1]
 [ 36 100   1]
 [ 31 151   1]
 [ 22 171   1]
 [ 33  80   0]
 [ 26 106   1]
 [ 18 117   1]
 [ 17  11   0]
 [ 13  10   0]
 [ 17  10   0]
 [ 12   9   0]]


In [11]:
dataTraining = np.concatenate((irisDataset[0:40,:],irisDataset[50:90,:]),axis=0)
dataTesting = np.concatenate((irisDataset[40:50,:],irisDataset[90:100,:]),axis=0)

In [12]:
print(dataTraining)
len(dataTraining)

[[ 26  74   0]
 [ 25  64   0]
 [ 29  70   0]
 [ 36  78   0]
 [ 20  45   0]
 [ 37  47   0]
 [ 36  82   1]
 [ 37  98   1]
 [ 32 116   1]
 [ 48  78   0]
 [ 37  88   1]
 [ 25  73   0]
 [ 42  75   0]
 [ 37  71   0]
 [ 23  74   0]
 [ 22  41   0]
 [ 19  35   0]
 [ 22  39   0]
 [ 23  87   1]
 [ 25  82   0]
 [ 39  65   0]
 [ 34  64   0]
 [ 32  76   0]
 [ 29  71   0]
 [ 33  57   0]
 [ 22  70   0]
 [ 14 107   1]
 [ 20 131   1]
 [ 17 105   1]
 [ 46  59   0]
 [ 15  81   0]
 [ 19  85   1]
 [ 36 143   1]
 [ 30 130   1]
 [ 19 129   1]
 [ 36 100   1]
 [ 31 151   1]
 [ 22 171   1]
 [ 33  80   0]
 [ 26 106   1]]


40

In [13]:
print(dataTesting)
len(dataTesting)

[[ 18 117   1]
 [ 17  11   0]
 [ 13  10   0]
 [ 17  10   0]
 [ 12   9   0]]


5

In [14]:
inputTraining = dataTraining[:, 0:2]
inputTesting = dataTesting[:, 0:2]
labelTraining = dataTraining[:,2]
labelTesting = dataTesting[:,2]

In [15]:
model = tree.DecisionTreeClassifier()

In [16]:
model = model.fit(inputTraining, labelTraining)

In [17]:
hasilPrediksi = model.predict(inputTesting)
print("label Sebenarnya", labelTesting)
print("hasil prediksi", hasilPrediksi)

label Sebenarnya [1 0 0 0 0]
hasil prediksi [1 0 0 0 0]


In [18]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("prediksi benar : ", prediksiBenar, "data")
print("prediksi salah : ", prediksiSalah, "data")
print("akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah) *100, "%")

prediksi benar :  5 data
prediksi salah :  0 data
akurasi :  100.0 %
