<a href="https://colab.research.google.com/github/nendyannisa/PrepocessingPencemaranUdara/blob/main/PrepocessingPencemaranUdara.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Pencemaran.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['DKI1 (Bunderan HI)' 52.0 18.0 26.0 74.0 13.0 74.0]
 ['DKI1 (Bunderan HI)' 40.0 19.0 25.0 64.0 13.0 64.0]
 ['DKI1 (Bunderan HI)' 41.0 17.0 29.0 70.0 12.0 70.0]
 ['DKI1 (Bunderan HI)' 56.0 23.0 36.0 78.0 11.0 78.0]
 ['DKI1 (Bunderan HI)' 42.0 18.0 20.0 45.0 11.0 45.0]
 ['DKI1 (Bunderan HI)' 58.0 24.0 37.0 47.0 18.0 58.0]
 ['DKI1 (Bunderan HI)' 89.0 34.0 36.0 82.0 23.0 89.0]
 ['DKI1 (Bunderan HI)' 67.0 25.0 37.0 98.0 22.0 98.0]
 ['DKI1 (Bunderan HI)' 58.0 22.0 32.0 116.0 21.0 116.0]
 ['DKI1 (Bunderan HI)' 75.0 20.0 48.0 78.0 25.0 78.0]
 ['DKI1 (Bunderan HI)' 45.0 13.0 37.0 88.0 12.0 88.0]
 ['DKI1 (Bunderan HI)' 54.0 21.0 25.0 73.0 13.0 73.0]
 ['DKI1 (Bunderan HI)' 66.0 24.0 42.0 75.0 17.0 75.0]
 ['DKI1 (Bunderan HI)' 55.0 21.0 37.0 71.0 15.0 71.0]
 ['DKI1 (Bunderan HI)' 36.0 17.0 23.0 74.0 7.0 74.0]
 ['DKI1 (Bunderan HI)' 33.0 20.0 22.0 41.0 8.0 41.0]
 ['DKI1 (Bunderan HI)' 29.0 15.0 19.0 35.0 5.0 35.0]
 ['DKI1 (Bunderan HI)' nan nan nan nan nan nan]
 ['DKI1 (Bunderan HI)' nan nan nan 

In [ ]:
print(y)

['SEDANG' 'SEDANG' 'SEDANG' 'SEDANG' 'BAIK' 'SEDANG' 'SEDANG' 'SEDANG'
 'TIDAK SEHAT' 'SEDANG' 'SEDANG' 'SEDANG' 'SEDANG' 'SEDANG' 'SEDANG'
 'BAIK' 'BAIK' 'TIDAK ADA DATA' 'TIDAK ADA DATA' 'TIDAK ADA DATA' 'BAIK'
 'SEDANG' 'SEDANG' 'SEDANG' 'SEDANG' 'TIDAK SEHAT' 'SEDANG' 'SEDANG'
 'SEDANG' 'SEDANG' 'SEDANG' 'TIDAK SEHAT' 'TIDAK SEHAT' 'TIDAK SEHAT'
 'SEDANG' 'SEDANG' 'SEDANG' 'TIDAK SEHAT' 'TIDAK SEHAT' 'TIDAK SEHAT'
 'SEDANG' 'TIDAK SEHAT' 'TIDAK SEHAT' 'SEDANG' 'TIDAK SEHAT' 'TIDAK SEHAT'
 'BAIK' 'BAIK' 'BAIK' 'BAIK']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:6])
x[:, 1:6] = imputer.transform(x[:, 1:6])

In [ ]:
print(x)

[['DKI1 (Bunderan HI)' 52.0 18.0 26.0 74.0 13.0 74.0]
 ['DKI1 (Bunderan HI)' 40.0 19.0 25.0 64.0 13.0 64.0]
 ['DKI1 (Bunderan HI)' 41.0 17.0 29.0 70.0 12.0 70.0]
 ['DKI1 (Bunderan HI)' 56.0 23.0 36.0 78.0 11.0 78.0]
 ['DKI1 (Bunderan HI)' 42.0 18.0 20.0 45.0 11.0 45.0]
 ['DKI1 (Bunderan HI)' 58.0 24.0 37.0 47.0 18.0 58.0]
 ['DKI1 (Bunderan HI)' 89.0 34.0 36.0 82.0 23.0 89.0]
 ['DKI1 (Bunderan HI)' 67.0 25.0 37.0 98.0 22.0 98.0]
 ['DKI1 (Bunderan HI)' 58.0 22.0 32.0 116.0 21.0 116.0]
 ['DKI1 (Bunderan HI)' 75.0 20.0 48.0 78.0 25.0 78.0]
 ['DKI1 (Bunderan HI)' 45.0 13.0 37.0 88.0 12.0 88.0]
 ['DKI1 (Bunderan HI)' 54.0 21.0 25.0 73.0 13.0 73.0]
 ['DKI1 (Bunderan HI)' 66.0 24.0 42.0 75.0 17.0 75.0]
 ['DKI1 (Bunderan HI)' 55.0 21.0 37.0 71.0 15.0 71.0]
 ['DKI1 (Bunderan HI)' 36.0 17.0 23.0 74.0 7.0 74.0]
 ['DKI1 (Bunderan HI)' 33.0 20.0 22.0 41.0 8.0 41.0]
 ['DKI1 (Bunderan HI)' 29.0 15.0 19.0 35.0 5.0 35.0]
 ['DKI1 (Bunderan HI)' 52.075 18.630434782608695 27.638297872340427
  80.9574468085

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 52.0 18.0 26.0 74.0 13.0 74.0]
 [1.0 0.0 40.0 19.0 25.0 64.0 13.0 64.0]
 [1.0 0.0 41.0 17.0 29.0 70.0 12.0 70.0]
 [1.0 0.0 56.0 23.0 36.0 78.0 11.0 78.0]
 [1.0 0.0 42.0 18.0 20.0 45.0 11.0 45.0]
 [1.0 0.0 58.0 24.0 37.0 47.0 18.0 58.0]
 [1.0 0.0 89.0 34.0 36.0 82.0 23.0 89.0]
 [1.0 0.0 67.0 25.0 37.0 98.0 22.0 98.0]
 [1.0 0.0 58.0 22.0 32.0 116.0 21.0 116.0]
 [1.0 0.0 75.0 20.0 48.0 78.0 25.0 78.0]
 [1.0 0.0 45.0 13.0 37.0 88.0 12.0 88.0]
 [1.0 0.0 54.0 21.0 25.0 73.0 13.0 73.0]
 [1.0 0.0 66.0 24.0 42.0 75.0 17.0 75.0]
 [1.0 0.0 55.0 21.0 37.0 71.0 15.0 71.0]
 [1.0 0.0 36.0 17.0 23.0 74.0 7.0 74.0]
 [1.0 0.0 33.0 20.0 22.0 41.0 8.0 41.0]
 [1.0 0.0 29.0 15.0 19.0 35.0 5.0 35.0]
 [1.0 0.0 52.075 18.630434782608695 27.638297872340427 80.95744680851064
  13.404255319148936 nan]
 [1.0 0.0 52.075 18.630434782608695 27.638297872340427 80.95744680851064
  13.404255319148936 nan]
 [1.0 0.0 52.075 18.630434782608695 27.638297872340427 80.95744680851064
  13.404255319148936 nan]
 [1.0 0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 1 1 1 0 1 1 1 3 1 1 1 1 1 1 0 0 2 2 2 0 1 1 1 1 3 1 1 1 1 1 3 3 3 1 1 1
 3 3 3 1 3 3 1 3 3 0 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 1.0 39.0 13.0 20.0 131.0 12.0 131.0]
 [0.0 1.0 57.0 17.0 19.0 129.0 19.0 129.0]
 [1.0 0.0 51.0 17.0 23.0 87.0 9.0 87.0]
 [0.0 1.0 56.0 16.0 19.0 85.0 18.0 85.0]
 [1.0 0.0 52.075 18.630434782608695 27.638297872340427 80.95744680851064
  13.404255319148936 nan]
 [0.0 1.0 53.0 16.0 22.0 171.0 11.0 171.0]
 [0.0 1.0 30.0 12.0 12.0 9.0 8.0 30.0]
 [1.0 0.0 52.075 15.0 35.0 65.0 12.0 65.0]
 [1.0 0.0 50.0 19.0 25.0 82.0 9.0 82.0]
 [1.0 0.0 55.0 21.0 37.0 71.0 15.0 71.0]
 [0.0 1.0 48.0 14.0 31.0 151.0 15.0 151.0]
 [1.0 0.0 52.075 18.630434782608695 27.638297872340427 80.95744680851064
  13.404255319148936 nan]
 [0.0 1.0 36.0 12.0 18.0 117.0 12.0 117.0]
 [1.0 0.0 52.075 18.0 34.0 64.0 8.0 64.0]
 [1.0 0.0 63.0 21.0 39.0 65.0 8.0 65.0]
 [1.0 0.0 42.0 18.0 20.0 45.0 11.0 45.0]
 [0.0 1.0 43.0 12.0 17.0 105.0 13.0 105.0]
 [1.0 0.0 36.0 17.0 23.0 74.0 7.0 74.0]
 [1.0 0.0 37.0 19.0 22.0 70.0 9.0 70.0]
 [1.0 0.0 45.0 13.0 37.0 88.0 12.0 88.0]
 [1.0 0.0 52.075 28.0 29.0 71.0 13.0 71.0]
 [0.0 1.0 52.

In [ ]:
print(y_train)

[3 3 1 1 2 3 0 1 1 1 3 2 3 1 1 0 3 1 1 1 1 3 1 2 0 3 1 1 0 1 0 1 0 1 1 1 3
 1 1 3]


In [ ]:
print(x_test)

[[1.0 0.0 52.075 21.0 32.0 76.0 11.0 76.0]
 [0.0 1.0 52.075 14.0 15.0 81.0 15.0 81.0]
 [0.0 1.0 82.0 25.0 36.0 100.0 17.0 100.0]
 [0.0 1.0 81.0 24.0 30.0 130.0 22.0 130.0]
 [1.0 0.0 41.0 17.0 29.0 70.0 12.0 70.0]
 [1.0 0.0 56.0 23.0 36.0 78.0 11.0 78.0]
 [0.0 1.0 25.0 13.0 17.0 10.0 9.0 25.0]
 [1.0 0.0 52.075 22.0 33.0 57.0 10.0 57.0]
 [0.0 1.0 34.0 13.0 17.0 11.0 10.0 34.0]
 [0.0 1.0 63.0 18.0 14.0 107.0 16.0 107.0]]


In [ ]:
print(y_test)

[1 1 1 3 1 1 0 1 0 3]


In [ ]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
x_train[:, 6:] = sc.fit_transform(x_train[:, 6:])
x_test[:, 6:] = sc.transform(x_test[:, 6:])

Scalling data

In [ ]:
print(x_train)

[[0.0 1.0 39.0 13.0 20.0 131.0 -0.3047575458499218 1.2461082936821972]
 [0.0 1.0 57.0 17.0 19.0 129.0 1.18672973692619 1.191834006611872]
 [1.0 0.0 51.0 17.0 23.0 87.0 -0.9439663813253983 0.052073978135041804]
 [0.0 1.0 56.0 16.0 19.0 85.0 0.9736601251010312 -0.0022003089352834455]
 [1.0 0.0 52.075 18.630434782608695 27.638297872340427 80.95744680851064
  -0.005553410095443572 nan]
 [0.0 1.0 53.0 16.0 22.0 171.0 -0.5178271576750807 2.331594035088702]
 [0.0 1.0 30.0 12.0 12.0 9.0 -1.1570359931505572 -1.4947432033692276]
 [1.0 0.0 52.075 15.0 35.0 65.0 -0.3047575458499218 -0.5449431796385359]
 [1.0 0.0 50.0 19.0 25.0 82.0 -0.9439663813253983 -0.08361173954077132]
 [1.0 0.0 55.0 21.0 37.0 71.0 0.33445128962555465 -0.38212031842756017]
 [0.0 1.0 48.0 14.0 31.0 151.0 0.33445128962555465 1.7888511643854497]
 [1.0 0.0 52.075 18.630434782608695 27.638297872340427 80.95744680851064
  -0.005553410095443572 nan]
 [0.0 1.0 36.0 12.0 18.0 117.0 -0.3047575458499218 0.8661882841899204]
 [1.0 0.0 52.0

In [ ]:
print(x_test)

[[1.0 0.0 52.075 21.0 32.0 76.0 -0.5178271576750807 -0.24643460075174706]
 [0.0 1.0 52.075 14.0 15.0 81.0 0.33445128962555465 -0.11074888307593393]
 [0.0 1.0 82.0 25.0 36.0 100.0 0.7605905132758723 0.4048568440921559]
 [0.0 1.0 81.0 24.0 30.0 130.0 1.8259385724016666 1.2189711501470346]
 [1.0 0.0 41.0 17.0 29.0 70.0 -0.3047575458499218 -0.4092574619627228]
 [1.0 0.0 56.0 23.0 36.0 78.0 -0.5178271576750807 -0.1921603136814218]
 [0.0 1.0 25.0 13.0 17.0 10.0 -0.9439663813253983 -1.630428921045041]
 [1.0 0.0 52.075 22.0 33.0 57.0 -0.7308967695002395 -0.7620403279198369]
 [0.0 1.0 34.0 13.0 17.0 11.0 -0.7308967695002395 -1.3861946292285772]
 [0.0 1.0 63.0 18.0 14.0 107.0 0.5475209014507135 0.5948168488382942]]
